<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canad</name>
   <tag></tag>
   <elementGuidId>48caa102-08df-4bf1-b761-3096d22edd10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine.navFooterLineDivider > ul > li:nth-of-type(3) > a.nav_a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e12a2c9-b1db-4f43-baab-e782d78461bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.ca/ref=footer_ca</value>
      <webElementGuid>b7ce4cb6-e66d-44f9-8327-d3fa3c9ca13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>0579ef05-0350-497a-942e-d50062ad7310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canadá</value>
      <webElementGuid>2db12cc7-75cf-415d-85f3-d388ff22f342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine navFooterLineDivider&quot;]/ul[1]/li[3]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>f3b12efe-0814-406c-be3d-6b385ccf063c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul/li[3]/a</value>
      <webElementGuid>06bbd70f-747e-47b2-ac8f-071534634b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Canadá')]</value>
      <webElementGuid>b47d6bbc-3c59-4ec8-b147-d54ba1122d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.ca/ref=footer_ca')]</value>
      <webElementGuid>6270567d-ca29-42c8-abb5-8f9923ea5de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[3]/a</value>
      <webElementGuid>84c80ff4-5df8-4700-aba2-564208cc1ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.ca/ref=footer_ca' and (text() = 'Canadá' or . = 'Canadá')]</value>
      <webElementGuid>8f020add-2e32-406f-8f72-a7746cc5550a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
