<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>China</name>
   <tag></tag>
   <elementGuidId>85f11a81-15f6-480a-b085-aa6fd07eb625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine.navFooterLineDivider > ul > li:nth-of-type(4) > a.nav_a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c4f25ae-3e76-4466-a69d-e28b349f742b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.cn/ref=footer_cn</value>
      <webElementGuid>9b075be2-d83a-4178-8e77-e40f4e095803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>c812e9ce-0011-4336-a39b-c2fb9206a982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>China</value>
      <webElementGuid>a2622fd2-bcce-41ad-9f48-eebf92e805f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine navFooterLineDivider&quot;]/ul[1]/li[4]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>459b306f-406a-4074-aa99-2aa5b5dd7539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul/li[4]/a</value>
      <webElementGuid>c69c5a80-f7bf-4e66-9aa0-b69e2b41d947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'China')]</value>
      <webElementGuid>a3cb73fd-eaea-47e1-a9f5-1fd8598d309d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.cn/ref=footer_cn')]</value>
      <webElementGuid>eb85c7fb-e111-427d-8688-b23d7a059d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[4]/a</value>
      <webElementGuid>17a7a2e1-cbc6-48aa-a229-bcdd8ce02d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.cn/ref=footer_cn' and (text() = 'China' or . = 'China')]</value>
      <webElementGuid>d99aee6f-988a-451e-90a6-dab9f97396b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
