<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Brazil</name>
   <tag></tag>
   <elementGuidId>5daaa582-3669-4ac3-baab-94037b22f57f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine > ul > li:nth-of-type(2) > a.nav_a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>201b44c6-a773-4c2d-b928-9b69a7ba6009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com.br/ref=footer_br</value>
      <webElementGuid>07d2bbd1-3239-4afe-8768-9353a629ccdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>80130fa5-5e5a-47f4-8dea-56f9207bbe82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brazil</value>
      <webElementGuid>dbf03695-e70b-44c4-9c79-f4bf0295fd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine&quot;]/ul[1]/li[2]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>d215f94f-e199-4895-b4ad-4f1bcbe84160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul/li[2]/a</value>
      <webElementGuid>cdabed8c-a6b7-42f5-bbfc-8e468b5978b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Brazil')]</value>
      <webElementGuid>a84d52b2-3288-44d0-b7cd-3f3b05c9e0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com.br/ref=footer_br')]</value>
      <webElementGuid>bfc8d8f1-cb66-4882-8690-061f1dc43032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]/a</value>
      <webElementGuid>de966692-8080-49c9-88a7-4b679225bd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com.br/ref=footer_br' and (text() = 'Brazil' or . = 'Brazil')]</value>
      <webElementGuid>ba4731da-cd9c-494f-9760-b0ad93b05a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
